export const SELECTED_TAB = 'SELECTED_TAB';

export const ITEM_TO_CREATE = 'ITEM_TO_CREATE';

export const NEW_CLUSTER_TITLE = 'NEW_CLUSTER_TITLE';

export const INDEPENDENT_ITEM_HEADING = 'INDEPENDENT_ITEM_HEADING';
export const INDEPENDENT_ITEM_CONTENT = 'INDEPENDENT_ITEM_CONTENT';

export const CREATE_INDEPENDENT_ITEM = 'CREATE_INDEPENDENT_ITEM';
