export const SELECTED_TAB = 'SELECTED_TAB';

export const ITEM_TO_CREATE = 'ITEM_TO_CREATE';

export const NEW_CLUSTER_TITLE = 'NEW_CLUSTER_TITLE';
export const NEW_CLUSTER_ITEM = 'NEW_CLUSTER_ITEM';
export const DELETE_CLUSTER = 'DELETE_CLUSTER';

export const INDEPENDENT_ITEM_HEADING = 'INDEPENDENT_ITEM_HEADING';
export const INDEPENDENT_ITEM_CONTENT = 'INDEPENDENT_ITEM_CONTENT';

export const CREATE_INDEPENDENT_ITEM = 'CREATE_INDEPENDENT_ITEM';
export const DELETE_INDEPENDENT_ITEM = 'DELETE_INDEPENDENT_ITEM';

export const SET_SELECTED_ID = 'SET_SELECTED_ID';
export const SELECTED_CLUSTER_ID = 'SELECTED_CLUSTER_ID';
export const SET_SELECTED_CLUSTER_ITEM_ID = 'SET_SELECTED_CLUSTER_ITEM_ID';
export const SET_SELECTED_INDEPENDENT_ITEM_ID = 'SET_SELECTED_INDEPENDENT_ITEM_ID';
export const CURRENTLY_SLECETED = 'CURRENTLY_SLECETED';
